"""add prevision date in bill

Revision ID: 3926d785f625
Revises: 9813f418ff10
Create Date: 2024-09-19 21:55:01.513810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3926d785f625"
down_revision: Union[str, None] = "9813f418ff10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contas_a_pagar_e_receber",
        sa.Column("data_previsao", sa.DateTime(), nullable=True),
    )
    op.execute("UPDATE contas_a_pagar_e_receber SET data_previsao = now()")
    op.alter_column("contas_a_pagar_e_receber", 'data_previsao', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contas_a_pagar_e_receber", "data_previsao")
    # ### end Alembic commands ###
