"""add bills date

Revision ID: 9813f418ff10
Revises: cbe3154eb79e
Create Date: 2024-09-18 22:41:58.963171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9813f418ff10"
down_revision: Union[str, None] = "cbe3154eb79e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contas_a_pagar_e_receber",
        sa.Column("data_baixa", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "contas_a_pagar_e_receber",
        sa.Column("valor_baixa", sa.Numeric(), nullable=True),
    )
    op.add_column(
        "contas_a_pagar_e_receber",
        sa.Column("esta_baixada", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contas_a_pagar_e_receber", "data_baixa")
    op.drop_column("contas_a_pagar_e_receber", "valor_baixa")
    op.drop_column("contas_a_pagar_e_receber", "esta_baixada")
    # ### end Alembic commands ###
